version: 0.2
phases:
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket devops-kuba --output-template-file outputtemplate.yaml
artifacts:
  files:
    - outputtemplate.yaml