version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14fj17mnezpkl"
s3_prefix = "sam-demo"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
